services:
  - type: web
    name: vedawell-backend
    runtime: python
    buildCommand: "cd backend"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port 10000"
    envVars:
      - key: HF_TOKEN
        sync: false